name: Run Arxiv Filter

on:
  schedule:
    # 北京时间 12:01 对应 UTC 时间 04:01
    - cron: '1 4 * * 1-5'  # 周一到周五 UTC 04:01 (北京时间 12:01)
  workflow_dispatch:  # 添加手动触发选项

jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      has_updates: ${{ steps.check.outputs.has_updates }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" > .env
        echo "MODEL_NAME=${{ secrets.MODEL_NAME }}" >> .env
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
    
    - name: Check for updates
      id: check
      run: python check_updates.py
      
    - name: Upload RSS cache
      if: steps.check.outputs.has_updates == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: rss-cache
        path: rss_cache.json
        retention-days: 1
    
  run-filter:
    needs: check-updates
    if: needs.check-updates.outputs.has_updates == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" > .env
        echo "MODEL_NAME=${{ secrets.MODEL_NAME }}" >> .env
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
    
    - name: Download cache from previous job
      uses: actions/download-artifact@v4
      with:
        name: rss-cache
        path: .
    
    - name: Run filter
      run: python run_filter.py
    
    - name: Generate RSS feed
      run: python generate_rss.py
    
    - name: Deploy RSS feed
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        keep_files: true
        commit_message: ${{ github.event.head_commit.message }}
    
    - name: Commit batch inference cache
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update batch inference cache [skip ci]'
        file_pattern: 'arxiv_updates/batch_results_*.json'
        commit_user_name: 'github-actions[bot]'
        commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
        skip_dirty_check: true 